services:
  - type: web
    name: vrgaus-deploy
    env: static
    buildCommand: echo "Static site - no build needed"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 